server:
  port: 8080
  servlet:
    context-path: /hwstore

database:
  url: jdbc:mysql://localhost:3306/hwshop?serverTimezone=UTC
  username: 'root'
  password: 'Gringotts'
  driverClassName: com.mysql.jdbc.Driver

hibernate:
  dialect: 'org.hibernate.dialect.MySQL5InnoDBDialect'
  show_sql: true
  format_sql: true
  hbm2ddl:
    auto: update
  id:
    new_generator_mappings: true

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false


